const GeoLayout mc_scarecrow_decap_head_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 26870),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 180, 102),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mc_scarecrow_decap_head_decap_head_mesh_layer_1_with_revert),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, mc_scarecrow_decap_head_decap_head_mesh_layer_4_with_revert),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
