extern const GeoLayout boo_coin_Spin_opt1[];
extern const GeoLayout boo_coin_Spin_opt2[];
extern const GeoLayout boo_coin_Spin_opt3[];
extern const GeoLayout boo_coin_Spin_opt4[];
extern const GeoLayout boo_coin_Spin_opt5[];
extern const GeoLayout boo_coin_Spin_opt6[];
extern const GeoLayout boo_coin_Spin_opt7[];
extern const GeoLayout boo_coin_Spin_opt8[];
extern const GeoLayout boo_coin_Spin_opt9[];
extern const GeoLayout boo_coin_Spin_opt10[];
extern const GeoLayout boo_coin_Spin_opt11[];
extern const GeoLayout boo_coin_Spin_opt12[];
extern const GeoLayout boo_coin_Spin_opt13[];
extern const GeoLayout boo_coin_Spin_opt14[];
extern const GeoLayout boo_coin_Spin_opt15[];
extern const GeoLayout boo_coin_Spin_opt16[];
extern const GeoLayout boo_coin_Spin_opt17[];
extern const GeoLayout boo_coin_Spin_opt18[];
extern const GeoLayout boo_coin_Spin_opt19[];
extern const GeoLayout boo_coin_Spin_opt20[];
extern const GeoLayout boo_coin_geo[];
extern u8 boo_coin_Boo_Coins_Shy_ci8[];
extern u8 boo_coin_Boo_Coins_Shy_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Joyous1_ci8[];
extern u8 boo_coin_Boo_Coins_Joyous1_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Joyous2_ci8[];
extern u8 boo_coin_Boo_Coins_Joyous2_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Joyous3_ci8[];
extern u8 boo_coin_Boo_Coins_Joyous3_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Side_ia8[];
extern u8 boo_coin_Boo_Coins_Smug1_ia8[];
extern u8 boo_coin_Boo_Coins_Smug2_ia8[];
extern u8 boo_coin_Boo_Coins_Smug3_ia8[];
extern u8 boo_coin_Boo_Coins_Tongue1_ci8[];
extern u8 boo_coin_Boo_Coins_Tongue1_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Tongue2_ci8[];
extern u8 boo_coin_Boo_Coins_Tongue2_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Tongue3_ci8[];
extern u8 boo_coin_Boo_Coins_Tongue3_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Blah1_ci8[];
extern u8 boo_coin_Boo_Coins_Blah1_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Blah2_ci8[];
extern u8 boo_coin_Boo_Coins_Blah2_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Blah3_ci8[];
extern u8 boo_coin_Boo_Coins_Blah3_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Dizzy1_ci8[];
extern u8 boo_coin_Boo_Coins_Dizzy1_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Dizzy2_ci8[];
extern u8 boo_coin_Boo_Coins_Dizzy2_pal_rgba16[];
extern u8 boo_coin_Boo_Coins_Dizzy3_ci8[];
extern u8 boo_coin_Boo_Coins_Dizzy3_pal_rgba16[];
extern Vtx boo_coin_dl_mesh_layer_4_vtx_0[4];
extern Gfx boo_coin_dl_mesh_layer_4_tri_0[];
extern Gfx mat_boo_coin_Boo_Coins_Shy[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Shy[];
extern Gfx mat_boo_coin_Boo_Coins_Joyous1[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Joyous1[];
extern Gfx mat_boo_coin_Boo_Coins_Joyous2[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Joyous2[];
extern Gfx mat_boo_coin_Boo_Coins_Joyous3[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Joyous3[];
extern Gfx mat_boo_coin_Boo_Coins_Side[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Side[];
extern Gfx mat_boo_coin_Boo_Coins_Smug1[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Smug1[];
extern Gfx mat_boo_coin_Boo_Coins_Smug2[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Smug2[];
extern Gfx mat_boo_coin_Boo_Coins_Smug3[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Smug3[];
extern Gfx mat_boo_coin_Boo_Coins_Tongue1[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Tongue1[];
extern Gfx mat_boo_coin_Boo_Coins_Tongue2[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Tongue2[];
extern Gfx mat_boo_coin_Boo_Coins_Tongue3[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Tongue3[];
extern Gfx mat_boo_coin_Boo_Coins_Blah1[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Blah1[];
extern Gfx mat_boo_coin_Boo_Coins_Blah2[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Blah2[];
extern Gfx mat_boo_coin_Boo_Coins_Blah3[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Blah3[];
extern Gfx mat_boo_coin_Boo_Coins_Dizzy1[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Dizzy1[];
extern Gfx mat_boo_coin_Boo_Coins_Dizzy2[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Dizzy2[];
extern Gfx mat_boo_coin_Boo_Coins_Dizzy3[];
extern Gfx mat_revert_boo_coin_Boo_Coins_Dizzy3[];
extern Gfx boo_coin_dl_mesh_layer_4[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Joyous1_0[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Joyous2_1[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Joyous3_2[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Side_3[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Smug1_4[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Smug2_5[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Smug3_6[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Tongue1_7[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Tongue2_8[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Tongue3_9[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Blah1_10[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Blah2_11[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Blah3_12[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Dizzy1_13[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Dizzy2_14[];
extern Gfx boo_coin_dl_mesh_layer_4_mat_override_Boo_Coins_Dizzy3_15[];
