const GeoLayout master_box_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 90, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, master_box_Bone_mesh_layer_1_with_revert),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, master_box_Bone_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 22, 20, master_box_Bone_002_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 22, -20, master_box_Bone_003_mesh_layer_4_with_revert),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
