extern const GeoLayout master_cap_stage_area_1_geo[];
extern const GeoLayout master_cap_stage_area_1[];
extern const Collision master_cap_stage_area_1_collision[];
extern const MacroObject master_cap_stage_area_1_macro_objs[];
extern Lights1 master_cap_stage_dl_Ground_lights;
extern Lights1 master_cap_stage_dl_Grate_lights;
extern Lights1 master_cap_stage_dl_Shingles_lights;
extern Vtx master_cap_stage_dl_Death_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx master_cap_stage_dl_Death_Plane_mesh_layer_5_vtx_0[4];
extern Gfx master_cap_stage_dl_Death_Plane_mesh_layer_5_tri_0[];
extern Vtx master_cap_stage_dl_Level_mesh_layer_1_vtx_cull[8];
extern Vtx master_cap_stage_dl_Level_mesh_layer_1_vtx_0[1076];
extern Gfx master_cap_stage_dl_Level_mesh_layer_1_tri_0[];
extern Vtx master_cap_stage_dl_Level_mesh_layer_1_vtx_1[12];
extern Gfx master_cap_stage_dl_Level_mesh_layer_1_tri_1[];
extern Vtx master_cap_stage_dl_Level_mesh_layer_5_vtx_cull[8];
extern Vtx master_cap_stage_dl_Level_mesh_layer_5_vtx_0[12];
extern Gfx master_cap_stage_dl_Level_mesh_layer_5_tri_0[];
extern Gfx mat_master_cap_stage_dl_f3dlite_material_001[];
extern Gfx mat_revert_master_cap_stage_dl_f3dlite_material_001[];
extern Gfx mat_master_cap_stage_dl_Ground[];
extern Gfx mat_revert_master_cap_stage_dl_Ground[];
extern Gfx mat_master_cap_stage_dl_Grate[];
extern Gfx mat_revert_master_cap_stage_dl_Grate[];
extern Gfx mat_master_cap_stage_dl_Shingles[];
extern Gfx mat_revert_master_cap_stage_dl_Shingles[];
extern Gfx master_cap_stage_dl_Death_Plane_mesh_layer_5[];
extern Gfx master_cap_stage_dl_Level_mesh_layer_1[];
extern Gfx master_cap_stage_dl_Level_mesh_layer_5[];
extern Gfx master_cap_stage_dl_final_revert_mesh_layer_5[];
extern Gfx master_cap_stage_dl_final_revert_mesh_layer_1[];
