const GeoLayout mc_scarecrow_mc_scarecrow_head_switch[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 106, 0, 0, 0, 0),
	GEO_RETURN(),
};
const GeoLayout mc_scarecrow_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 26870),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 180, 102),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mc_scarecrow_root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, mc_scarecrow_body_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 195, 0, mc_scarecrow_body_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mc_scarecrow_body_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 86, 0, mc_scarecrow_arm_l_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 158, 2, 0, mc_scarecrow_hand_l_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -55, 86, 0, mc_scarecrow_arm_r_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -158, 2, 0, mc_scarecrow_hand_r_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mc_scarecrow_cape1_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 97, -44, mc_scarecrow_cape1_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mc_scarecrow_cape2_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -135, -66, mc_scarecrow_cape2_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(0, mc_scarecrow_switch),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 106, 0, mc_scarecrow_head_mesh_layer_1_with_revert),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, mc_scarecrow_head_mesh_layer_4_with_revert),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, mc_scarecrow_mc_scarecrow_head_switch),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
